# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUi(object):
    def setupUi(self, JarvisUi):
        JarvisUi.setObjectName("JarvisUi")
        JarvisUi.resize(1920, 1069)
        self.centralwidget = QtWidgets.QWidget(JarvisUi)
        self.centralwidget.setObjectName("centralwidget")
        self.B_G_1 = QtWidgets.QLabel(self.centralwidget)
        self.B_G_1.setGeometry(QtCore.QRect(-640, -30, 2591, 1151))
        self.B_G_1.setText("")
        self.B_G_1.setPixmap(QtGui.QPixmap("../../GUI materiaol/G.U.I Material/B.G/Black_Template.jpg"))
        self.B_G_1.setScaledContents(True)
        self.B_G_1.setObjectName("B_G_1")
        self.B_G_2 = QtWidgets.QLabel(self.centralwidget)
        self.B_G_2.setGeometry(QtCore.QRect(20, 20, 741, 481))
        self.B_G_2.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.B_G_2.setText("")
        self.B_G_2.setObjectName("B_G_2")
        self.B_G_3 = QtWidgets.QLabel(self.centralwidget)
        self.B_G_3.setGeometry(QtCore.QRect(770, 20, 671, 481))
        self.B_G_3.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.B_G_3.setText("")
        self.B_G_3.setObjectName("B_G_3")
        self.gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(30, 30, 721, 461))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap("../../GUI materiaol/G.U.I Material/B.G/Iron_Template_1.gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")
        self.gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif_2.setGeometry(QtCore.QRect(780, 30, 651, 461))
        self.gif_2.setText("")
        self.gif_2.setPixmap(QtGui.QPixmap("../../GUI materiaol/G.U.I Material/ExtraGui/live.gif"))
        self.gif_2.setScaledContents(True)
        self.gif_2.setObjectName("gif_2")
        self.gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.gif_3.setGeometry(QtCore.QRect(-180, 460, 891, 611))
        self.gif_3.setText("")
        self.gif_3.setPixmap(QtGui.QPixmap("../../GUI materiaol/G.U.I Material/VoiceReg/__1.gif"))
        self.gif_3.setScaledContents(True)
        self.gif_3.setObjectName("gif_3")
        self.B_G_5 = QtWidgets.QLabel(self.centralwidget)
        self.B_G_5.setGeometry(QtCore.QRect(1450, 20, 451, 341))
        self.B_G_5.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.B_G_5.setText("")
        self.B_G_5.setObjectName("B_G_5")
        self.gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.gif_4.setGeometry(QtCore.QRect(1460, 30, 431, 321))
        self.gif_4.setText("")
        self.gif_4.setPixmap(QtGui.QPixmap("../../GUI materiaol/G.U.I Material/ExtraGui/Earth_Template.gif"))
        self.gif_4.setScaledContents(True)
        self.gif_4.setObjectName("gif_4")
        self.Text_time = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_time.setGeometry(QtCore.QRect(1450, 850, 481, 91))
        self.Text_time.setStyleSheet("background-color:Transparent;\n"
"font: 36pt \"MS Shell Dlg 2\";\n"
"border-radius:None;\n"
"color: rgb(0, 170, 255);\n"
"\n"
"")
        self.Text_time.setObjectName("Text_time")
        self.B_G_6 = QtWidgets.QLabel(self.centralwidget)
        self.B_G_6.setGeometry(QtCore.QRect(1400, 840, 501, 111))
        self.B_G_6.setText("")
        self.B_G_6.setPixmap(QtGui.QPixmap("../../GUI materiaol/G.U.I Material/B.G/gggf.jpg"))
        self.B_G_6.setScaledContents(True)
        self.B_G_6.setObjectName("B_G_6")
        self.B_G_7 = QtWidgets.QLabel(self.centralwidget)
        self.B_G_7.setGeometry(QtCore.QRect(1400, 720, 501, 111))
        self.B_G_7.setText("")
        self.B_G_7.setPixmap(QtGui.QPixmap("../../GUI materiaol/G.U.I Material/B.G/gggf.jpg"))
        self.B_G_7.setScaledContents(True)
        self.B_G_7.setObjectName("B_G_7")
        self.Date = QtWidgets.QTextBrowser(self.centralwidget)
        self.Date.setGeometry(QtCore.QRect(1450, 730, 481, 91))
        self.Date.setStyleSheet("background-color:Transparent;\n"
"font: 36pt \"MS Shell Dlg 2\";\n"
"border-radius:None;\n"
"color: rgb(0, 170, 255);\n"
"\n"
"")
        self.Date.setObjectName("Date")
        self.Day = QtWidgets.QTextBrowser(self.centralwidget)
        self.Day.setGeometry(QtCore.QRect(1450, 610, 481, 91))
        self.Day.setStyleSheet("background-color:Transparent;\n"
"font: 36pt \"MS Shell Dlg 2\";\n"
"border-radius:None;\n"
"color: rgb(0, 170, 255);\n"
"\n"
"")
        self.Day.setObjectName("Day")
        self.B_G_8 = QtWidgets.QLabel(self.centralwidget)
        self.B_G_8.setGeometry(QtCore.QRect(1400, 600, 501, 111))
        self.B_G_8.setText("")
        self.B_G_8.setPixmap(QtGui.QPixmap("../../GUI materiaol/G.U.I Material/B.G/gggf.jpg"))
        self.B_G_8.setScaledContents(True)
        self.B_G_8.setObjectName("B_G_8")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(1460, 380, 201, 61))
        self.pushButton_start.setStyleSheet("background-color:Transperent;\n"
"font: 24pt \"MS Shell Dlg 2\";\n"
"\n"
"border-radius:None;\n"
"color: rgb(0, 170, 255);")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_exite = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exite.setGeometry(QtCore.QRect(1690, 380, 201, 61))
        self.pushButton_exite.setStyleSheet("background-color:Transperent;\n"
"font: 24pt \"MS Shell Dlg 2\";\n"
"\n"
"border-radius:None;\n"
"color: rgb(0, 170, 255);\n"
"")
        self.pushButton_exite.setObjectName("pushButton_exite")
        self.B_G_9 = QtWidgets.QLabel(self.centralwidget)
        self.B_G_9.setGeometry(QtCore.QRect(1450, 370, 221, 81))
        self.B_G_9.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.B_G_9.setText("")
        self.B_G_9.setObjectName("B_G_9")
        self.B_G_10 = QtWidgets.QLabel(self.centralwidget)
        self.B_G_10.setGeometry(QtCore.QRect(1680, 370, 221, 81))
        self.B_G_10.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.B_G_10.setText("")
        self.B_G_10.setObjectName("B_G_10")
        self.pushButton_yt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_yt.setGeometry(QtCore.QRect(820, 520, 181, 61))
        self.pushButton_yt.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_yt.setObjectName("pushButton_yt")
        self.pushButton_chrome = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chrome.setGeometry(QtCore.QRect(1010, 520, 171, 61))
        self.pushButton_chrome.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_chrome.setObjectName("pushButton_chrome")
        self.pushButton_whatsapp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_whatsapp.setGeometry(QtCore.QRect(1190, 520, 171, 61))
        self.pushButton_whatsapp.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_whatsapp.setObjectName("pushButton_whatsapp")
        self.B_G_1.raise_()
        self.B_G_8.raise_()
        self.B_G_6.raise_()
        self.gif_3.raise_()
        self.B_G_2.raise_()
        self.B_G_3.raise_()
        self.gif_1.raise_()
        self.gif_2.raise_()
        self.B_G_5.raise_()
        self.gif_4.raise_()
        self.Text_time.raise_()
        self.B_G_7.raise_()
        self.Date.raise_()
        self.Day.raise_()
        self.B_G_9.raise_()
        self.pushButton_start.raise_()
        self.B_G_10.raise_()
        self.pushButton_exite.raise_()
        self.pushButton_yt.raise_()
        self.pushButton_chrome.raise_()
        self.pushButton_whatsapp.raise_()
        JarvisUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUi)
        QtCore.QMetaObject.connectSlotsByName(JarvisUi)

    def retranslateUi(self, JarvisUi):
        _translate = QtCore.QCoreApplication.translate
        JarvisUi.setWindowTitle(_translate("JarvisUi", "MainWindow"))
        self.Text_time.setHtml(_translate("JarvisUi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:36pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Date.setHtml(_translate("JarvisUi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:36pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Day.setHtml(_translate("JarvisUi", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:36pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_start.setText(_translate("JarvisUi", "START"))
        self.pushButton_exite.setText(_translate("JarvisUi", "EXITE"))
        self.pushButton_yt.setText(_translate("JarvisUi", "YouTube"))
        self.pushButton_chrome.setText(_translate("JarvisUi", "Chrome"))
        self.pushButton_whatsapp.setText(_translate("JarvisUi", "WhatsApp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUi = QtWidgets.QMainWindow()
    ui = Ui_JarvisUi()
    ui.setupUi(JarvisUi)
    JarvisUi.show()
    sys.exit(app.exec_())
